### ISSUE TITLE
Python +3.8

### ISSUE THREAD

**Issue by alvarofpp** [UFRN-URNAI/urnai-tools#38]
Python 3.6 has not received any support since [22 Dec 2016](https://endoflife.date/python). We need to update references to Python 3.6 to a new version, preferably +3.8.

**Comment by elliotwutingfeng** [comment]
Let me try this

**Comment by alvarofpp** [comment]
@elliotwutingfeng The `requirements.txt` has been generated using Python 3.10, so I think that only necessary changes the `Dockerfile` and try to build the image. After that, you can test using the package in one script just to make sure.
