### ISSUE TITLE
Update CI workflow

### ISSUE THREAD

**Issue by alvarofpp** [UFRN-URNAI/urnai-tools#42]
Currently, the repo has two workflows (`linters.yml` and `tests.yml`). We can merge those workflows into one workflow with two jobs. The linter job must execute in a Docker container (`urnai/linter:latest`). The new workflow must be:

```mermaid
  graph LR;
      L[Lint]-->T[Tests];
```

**Comment by KehindeBello** [comment]
Can I be assigned this issue? I'll love to work on it

**Comment by alvarofpp** [comment]
@KehindeBello We don't assign the issue to one person, so other people can also work on the issue. Send your PR referencing the issue, your changes will be welcome.
