### ISSUE TITLE
Fix linter job

### ISSUE THREAD

**Issue by alvarofpp** [UFRN-URNAI/urnai-tools#44]
The `make lint` command works locally, but when it is run in the `ci` pipeline it throws an error (see [here](https://github.com/UFRN-URNAI/urnai-tools/actions/runs/3245414969/jobs/5323285432#step:3:62)) and doesn't check anything. This must be corrected so that the linter can execute its commands correctly.

An extra is to have this job run in a container from the `urnai/linter:latest` image.

**Comment by sudiptob2** [comment]
Interesting, I use [act](https://github.com/nektos/act) for testing workflows locally and the workflow does run properly on my local machine. I will investigate this issue further.
