### ISSUE TITLE
Create base classes for Action

### ISSUE THREAD

**Issue by alvarofpp** [UFRN-URNAI/urnai-tools#67]
We should have a base class for developing agent actions, these would be the micro-actions. In addition, we need a class for collecting actions, these would be macro-actions. These classes need to have methods that make it possible to know whether or not it is possible to perform that action.

Suggestions:

- Class names: `ActionBase` (micro-action) and `ChainOfActionsBase` (macro-actions).
- Class paths: `urnai.actions`.

Notes:

- This is an abstract class, so it is important that it inherits from `abc.ABC`.

**Comment by CinquilCinquil** [comment]
Hello, i would like some help on this issue.
I dont know exactly where to go from here, should i add methods, like the ones i commented on the code, for all possible actions of a SC2 player?

**Comment by alvarofpp** [comment]
For this issue, what you need to do is create abstract classes that will be used to create the classes of the action or set of actions. Defining methods and attributes is up to you. You can sketch something out, up the code and we can discuss your approach.

**Comment by CinquilCinquil** [comment]
I thought the methods from [here](https://github.com/UFRN-URNAI/urnai-tools/blob/add8f22a2084e5027548f1e861bf55745bb65f45/urnai/agents/actions/base/abwrapper.py) suited the task, so i distributed them between the 2 files (with a few modifications). What do you think?

**Comment by alvarofpp** [comment]
The file you mentioned refers to #68 and not to the issue we're discussing.

**Comment by alvarofpp** [comment]
Try to think about what is necessary for an `Action`. In my case, I think that an `Action` requires an identifier (maybe `self.id`), a condition to occur (maybe `self.check()`) and a method to execute it (maybe `self.run()`). Try to think about the `Action` and a set of `Actions`.

**Comment by CinquilCinquil** [comment]
Hey! Just commenting in case you did not receive a notification for those 2 commits. I'm wating to see if they have any problems.

**Comment by alvarofpp** [comment]
Hey @CinquilCinquil, if possible open a PR, it's better to see your changes there than commit by commit.
